apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-new
  namespace: 3t
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc

