apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc # Name of your Persistent Volume Claim
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi